### ISSUE TITLE
Complex cache key wildcards not matching

### ISSUE THREAD

**Issue by shaffe-fr** [spatie/blink#11]
Hello,
I'm using blink to dynamically cache fields from models and I'm using the full namespace as cache key.
The wildcards matching doesn't work because of the back-slashes.

A fix would be to use the FNM_NOESCAPE flag on the fnmatch function in the getKeysMatching method.

```php
fnmatch('App\Models\Post|slug|id|*', 'App\Models\Post|slug|id|my-post'); // returns false
fnmatch('App\Models\Post|slug|id|*', 'App\Models\Post|slug|id|my-post', FNM_NOESCAPE); // returns true
```
Would you consider integrating this fix?

Regards,
Karel

**Comment by peter279k** [comment]
It seems that you want to add a optional argument for completing your issue?

I think it's fine to create the PR to do that :+1: .

**Comment by freekmurze** [comment]
We'd accept a PR with tests that fixes this.
