### ISSUE TITLE
Stare challenge with Laravel

### ISSUE THREAD

**Issue by ildyria** [spatie/blink#23]
Hi, I just found out about this repository while browsing on https://spatie.be/open-source/packages

How does this differs from the *Laravel Cache* system (aside from the single request TTL)?
What I mean is, Is there any benefits of using *Blink* over *Laravel Cache* system? 

Thanks you

**Comment by freekmurze** [comment]
We use blink for some request cache and normal cache for things that should be cache across requests.

**Comment by ildyria** [comment]
Thank you. :+1:
