### ISSUE TITLE
Support PHP 8.1

### ISSUE THREAD

**Issue by edalzell** [spatie/blink#29]
Using version 1.1.3, I'm seeing this in my logs, on PHP8.1:

<img width="1237" alt="CleanShot 2022-01-04 at 15 25 13@2x" src="https://user-images.githubusercontent.com/6069653/148137519-87ad9297-3be9-4dc2-8202-2161c704a99d.png">

**Comment by freekmurze** [comment]
I accept a PR that fixes this. Probably those type hints will have to be added.

**Comment by edalzell** [comment]
Perfect, I was going to ask you if you wanted the hints or that #ReturnValueMayChange thingy. The hints are PHP 8+ only, right?

**Comment by freekmurze** [comment]
We'll handle it in the PR
