### ISSUE TITLE
[Feature] Conditional Once

### ISSUE THREAD

**Issue by jasonvarga** [spatie/blink#31]
Would you be open to a PR that would make the `once` method conditional?

We have a situation where we have some code inside a `Blink::once` closure, but sometimes we want to bypass it and just run the closure.

How about if you pass `null`/`false` as the `$key`, it just executes the closure?

It would allow us to change something like this:

```php
$stuff = function () {
  // do stuff
};

if ($useBlink) {
  return $stuff();
} else {
  return Blink::once('foo', $stuff);
}
```

into this:

```php
return Blink::once($useBlink ? 'foo' : null, function () {
  // do stuff
});
```

Or maybe a new method like `onceIf` if you don't want to change how `once` works:

```php
return Blink::onceIf($useBlink, 'foo', function () {
  // do stuff
});
```

**Comment by freekmurze** [comment]
`onceIf` seems like the way to go! 

Should you PR this, make sure to update readme and tests. 

Thanks!
